name: intl_phone_field
description: A customised Flutter TextFormField to input international phone number along with country code.
version: 3.1.1
homepage: https://github.com/vanshg395/intl_phone_field

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0

flutter:
  assets:
    - assets/flags/
